version: '3.9'

networks:
  projectNet:
    driver: bridge

services:
  bd:
    container_name: DB
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Projeto123
      - MSSQL_PID=Express
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - 1455:1433
    networks:
      - projectNet
  api:
    container_name: API
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - 4000:80
    networks:
      - projectNet
    depends_on:
      - bd